# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title EX correlation matrix function
#' @description generate exchangable working correlation matrix
#' @param t Specify matrix dimensions
#' @param alpha Specify the correlation parameter
#' @return EX correlation matrix with t_dimensions and alpha_parameter
#' @examples
#' \dontrun{
#' t <- 5
#' alpha <- 0.5
#' exchCpp(t,alpha)
#' }
#' @export
exchCpp <- function(t, alpha) {
    .Call('_SA24204141_exchCpp', PACKAGE = 'SA24204141', t, alpha)
}

#' @title AR1 correlation matrix function
#' @description generate autoregression working correlation matrix
#' @param t Specify matrix dimensions
#' @param alpha Specify the correlation parameter
#' @return AR1 correlation matrix with t_dimensions and alpha_parameter
#' @examples
#' \dontrun{
#' t <- 5
#' alpha <- 0.5
#' ar1Cpp(t,alpha)
#' }
#' @export
ar1Cpp <- function(t, alpha) {
    .Call('_SA24204141_ar1Cpp', PACKAGE = 'SA24204141', t, alpha)
}

#' @title ST correlation matrix function
#' @description generate stationary working correlation matrix
#' @param t Specify matrix dimensions
#' @param a Specify non-diagonal element
#' @return ST correlation matrix with t_dimensions and non-diagonal element a
#' @examples
#' \dontrun{
#' t <- 6
#' a <- c(0.5,0.4,0.3,-0.2,-0.1)
#' statCpp(t,a)
#' }
#' @export
statCpp <- function(t, a) {
    .Call('_SA24204141_statCpp', PACKAGE = 'SA24204141', t, a)
}

